name: ukk
description: A new Flutter project.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies (gunakan versi terbaru)
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.7.0  # Jika menggunakan autentikasi

  # Supabase untuk database alternatif
  supabase_flutter: ^2.8.3

  # Ikon tambahan
  cupertino_icons: ^1.0.6

  flutter_lints: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
